### ISSUE TITLE
install fails on CentOS 7

### ISSUE THREAD

**Issue by dunn** [Gargron/blurhash#1]
Running `gem install blurhash` under Ruby 2.6.1 (recommended for Mastodon) installed via rbenv on CentOS 7: https://gist.github.com/dunn/f87508f4549fceb061c0206dfca241ce

My guess is that it's because `arch_hdrdir`, which is used by the include flags, is hardcoded to Ruby 2.4.0: https://github.com/Gargron/blurhash/blob/master/ext/blurhash/Makefile#L17

**Comment by mherrb** [comment]
Same issue on Debian 8 with gcc 4.9

**Comment by salvadorpla** [comment]
Yes, it fails on Centos 7 so can't update to Mastodon v2.8.1:

An error occurred while installing blurhash (0.1.2), and Bundler cannot continue.
Make sure that `gem install blurhash -v '0.1.2' --source 'https://rubygems.org/'` succeeds before bundling.

**Comment by Gargron** [comment]
It appears to me that maybe the Makefile should not be committed to the repository. Oversight on my part, first C port in Ruby!

**Comment by Gargron** [comment]
Upon closer investigation, I don't think the Makefile is the issue per se. It should indeed not be committed into the repository because it gets auto-generated during `gem install` (so the hardcoded values are not the source of this problem!), but the instructions for generating the Makefile seem to be missing some compile flags for the exact flavour of the C code in encode.c

**Comment by TheRealKingS** [comment]
Same Error on CentOS 7:

`Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /home/mastodon-myifn/live/vendor/bundle/ruby/2.6.0/gems/blurhash-0.1.2/ext/blurhash
/home/mastodon-myifn/.rbenv/versions/2.6.1/bin/ruby -I
/home/mastodon-myifn/.rbenv/versions/2.6.1/lib/ruby/site_ruby/2.6.0 -r ./siteconf20190504-31315-80msis.rb extconf.rb
creating Makefile

current directory: /home/mastodon-myifn/live/vendor/bundle/ruby/2.6.0/gems/blurhash-0.1.2/ext/blurhash
make "DESTDIR=" clean

current directory: /home/mastodon-myifn/live/vendor/bundle/ruby/2.6.0/gems/blurhash-0.1.2/ext/blurhash
make "DESTDIR="
compiling encode.c
encode.c: In function ‘blurHashForPixels’:
encode.c:25:2: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  float factors[yComponents][xComponents][3];
  ^
encode.c:28:2: error: ‘for’ loop initial declarations are only allowed in C99 mode
  for(int y = 0; y < yComponents; y++) {
  ^
encode.c:28:2: note: use option -std=c99 or -std=gnu99 to compile your code
encode.c:29:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for(int x = 0; x < xComponents; x++) {
   ^
encode.c:37:2: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  float *dc = factors[0][0];
  ^
encode.c:45:2: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  float maximumValue;
  ^
encode.c:48:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for(int i = 0; i < acCount * 3; i++) {
   ^
encode.c:52:3: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
   int quantisedMaximumValue = fmaxf(0, fminf(82, floorf(actualMaximumValue * 166 - 0.5)));
   ^
encode.c:62:2: error: ‘for’ loop initial declarations are only allowed in C99 mode
  for(int i = 0; i < acCount; i++) {
  ^
encode.c: In function ‘multiplyBasisFunction’:
encode.c:75:2: error: ‘for’ loop initial declarations are only allowed in C99 mode
  for(int y = 0; y < height; y++) {
  ^
encode.c:76:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for(int x = 0; x < width; x++) {
   ^
encode.c:84:2: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  float scale = normalisation / (width * height);
  ^
encode.c: In function ‘encode_int’:
encode.c:129:2: error: ‘for’ loop initial declarations are only allowed in C99 mode
  for(int i = 0; i < length - 1; i++) divisor *= 83;
  ^
encode.c:131:10: error: redefinition of ‘i’
  for(int i = 0; i < length; i++) {
          ^
encode.c:129:10: note: previous definition of ‘i’ was here
  for(int i = 0; i < length - 1; i++) divisor *= 83;
          ^
encode.c:131:2: error: ‘for’ loop initial declarations are only allowed in C99 mode
  for(int i = 0; i < length; i++) {
  ^
encode.c: At top level:
cc1: warning: unrecognized command line option "-Wno-tautological-compare" [enabled by default]
cc1: warning: unrecognized command line option "-Wno-self-assign" [enabled by default]
cc1: warning: unrecognized command line option "-Wno-parentheses-equality" [enabled by default]
cc1: warning: unrecognized command line option "-Wno-constant-logical-operand" [enabled by default]
cc1: warning: unrecognized command line option "-Wno-cast-function-type" [enabled by default]
make: *** [encode.o] Error 1

make failed, exit code 2

Gem files will remain installed in /home/mastodon-myifn/live/vendor/bundle/ruby/2.6.0/gems/blurhash-0.1.2 for
inspection.
Results logged to
/home/mastodon-myifn/live/vendor/bundle/ruby/2.6.0/extensions/x86_64-linux/2.6.0-static/blurhash-0.1.2/gem_make.out

An error occurred while installing blurhash (0.1.2), and Bundler cannot continue.
Make sure that `gem install blurhash -v '0.1.2' --source 'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  blurhash`

**Comment by Gargron** [comment]
@salvadorpla @dunn @mherrb Can you update your Mastodon to master branch after commit f086517 and tell me if that has resolved your problem?

**Comment by Eleix** [comment]
Woo! Using master branch with the fixes gets blurhash to bundle build successfully on Ubuntu 18.04 LTS. 👍

**Comment by salvadorpla** [comment]
@Gargron great! Worked like a charm in Centos 7! Thank you.

**Comment by mherrb** [comment]
Worked for debian 8 too. Thanks !
