### ISSUE TITLE
warning: rb_safe_level will be removed in Ruby 3.0

### ISSUE THREAD

**Issue by RomanMaluf-Vaypol** [Gargron/blurhash#10]
I recently install blurhash gem in a project with rails 6 and ruby 2.7 
And i have many warning messages
![image](https://user-images.githubusercontent.com/56037766/107640153-9d77f500-6c50-11eb-8da8-7b5612e484d8.png)
This messages come from ffi Gem version

**Comment by Gargron** [comment]
Fixed by #12 (or will be in next release)
