### ISSUE TITLE
how to display text version of image?

### ISSUE THREAD

**Issue by jbeyer05** [Gargron/blurhash#2]
This looks very interesting, but I haven't been able to find any documentation on how to actually display the low resolution, text version of the image.  I tried with <img src="data:image/....">, but that didn't seem to work for gif, jpg or png.

**Comment by Gargron** [comment]
You need a decoder to turn the string back into pixels. There is a JavaScript decoder on NPM (`npm install blurhash`) and you can see the example usage here:

https://github.com/tootsuite/mastodon/blob/v2.8.2/app/javascript/mastodon/components/media_gallery.js#L84-L92

**Comment by jbeyer05** [comment]
Oh, apologies. It's been a long time since I created the issue. I think I thought at the time that the text encoded version was to be displayed via a data:uri tag on an <img> element.
