### ISSUE TITLE
Algorithm documentation

### ISSUE THREAD

**Issue by benjaminbillet** [Gargron/blurhash#3]
Would it be possible to have a better description of the algorithm itself (the rationales and core mechanisms)?. The C code is readable but don't give much information about how and why this thing works better than, for example, interpolating k pixels of the picture.

(this not an issue per se, more like an improvement)

**Comment by Gargron** [comment]
cc @dagagren

**Comment by DagAgren** [comment]
There will be a proper release of this with documentation and explanations, but it is dependent on arranging it at work since it's a work project, so I can't guarantee when.

As for interpolating pixels: It looks awful, and this looks nice, with slightly less data. That's about it!

**Comment by benjaminbillet** [comment]
"it looks awful, and this looks nice" doesn't help much for understanding, but okay, I'll wait for the proper release with documentation. Thanks :)

**Comment by DagAgren** [comment]
Done: https://github.com/woltapp/blurhash
