### ISSUE TITLE
Documentation for Minimagick

### ISSUE THREAD

**Issue by boardfish** [Gargron/blurhash#7]
Rails 6 seems to standardise on [minimagick](https://github.com/minimagick/minimagick) or vips for image processing. It seems optimal to use this over RMagick in just about any case.

I'm going to explore which methods need to be used to get minimagick to export data to Blurhash in the right way, with intent to make a PR to document them after I do. My questions are:

1. Does anyone know how to do this already, and if so, would they like to take responsibility for documenting it?
2. Should documentation on minimagick replace (or otherwise supersede) documentation for RMagick? If so, how? Straight-up delete or just move RMagick to an addendum?

**Comment by coding-chimp** [comment]
Okay, I went a little bit down the rabbit whole on this, so I'm just gonna share what I found. This is how you can use blurhash with RMagick, MiniMagick & Vips:

```ruby
path = 'path/to/an/image'

# RMagick
image = Magick::ImageList.new(path)
Blurhash.encode(image.columns, image.rows, image.export_pixels)

# MiniMagick
image = MiniMagick::Image.open(path)
Blurhash.encode(image.width, image.height, image.get_pixels.flatten)

# Vips
image = Vips::Image.new_from_file(path)
Blurhash.encode(image.width, image.height, image.to_a.flatten)
```

MiniMagick's `get_pixels` and Vips' `to_a` will give you a matrix of pixels and RMagick's `export_pixels` gives you a a flat list of pixels instead. Blurhash expects the flat list, so we have to flatten the matrices. The resulting hash is the same for all of them.

Now, depending on the number of pixels, building a matrix and then tearing it down again in ruby, might not give you the best performance. I'm mostly using Vips lately so I have a version where I extract the pixels myself. I more or less just copied the [to_a method](https://github.com/libvips/ruby-vips/blob/94cd429a4af461f654eb50bb79508ae8763970cf/lib/vips/image.rb#L1056-L1085) and deleted what we don't need.

```ruby
mapping = {
  char: 'c',
  uchar: 'C',
  short: 's_',
  ushort: 'S_',
  int: 'i_',
  uint: 'I_',
  float: 'f',
  double: 'd',
  complex: 'f',
  dpcomplex: 'd'
}

image = Vips::Image.new_from_file(path)
template = mapping[image.format] + '*'
pixels = image.write_to_memory.unpack(template)
Blurhash.encode(image.width, image.height, pixels)
```
 
This does speed up things, but RMagick still has slightly better performance for me. This benchmark was made with a small (403x302) image:

```
Comparison:
             RMagick:        9.7 i/s
         Vips Manual:        9.0 i/s - 1.07x  slower
                Vips:        6.7 i/s - 1.45x  slower
          MiniMagick:        5.5 i/s - 1.75x  slower
```

If you don't need any other image processing, RMagick actually looks like a valid choice for this, so I would just keep it documented?

**Comment by boardfish** [comment]
Wow, I wasn't expecting such depth! Thank you for your response.

I have to say, before writing this issue, I really didn't know enough about the R/Minimagick situation. It's not a massive dependency or cause of lag by any means since I've started using it. RMagick and Minimagick serve very different purposes. 

Thanks for showing me how this all comes together.
